"""HTML surgery helpers for one-off restructures of an audit-report HTML
(the file written alongside the PDF by ``report_generator._render_to_pdf``).

Born out of M7.6 Part B (Ellen-handoff). The same operations recur every
time someone needs to drop a section, merge subsections, insert an
external comment block, or recompute count badges after content cuts.
Instead of writing a fresh 350-line script each time, drive it from this
module:

    from compliance_engine.report_surgery import ReportSurgery

    (ReportSurgery
        .from_path("audit_report_24.3.html")
        .remove_subsection("sec-2-6")              # drop a plot
        .rename_subsection("sec-3-4",
                           "3.4 תנועה — רחבות כיבוי אש")
        .merge_subsection_rows("sec-3-7",
                               ["sec-3-8", "sec-3-9"])
        .remove_chapter_range("sec-m4-sidecar", "sec-3")  # §2א/2ב/2ג
        .remove_chapter_range("sec-5", "</body>")
        .insert_html_at_subsection_end("sec-3-7",
                                       _ARCHITECT_BLOCK_HTML)
        .replace_text("פרק 5 — היקף הסקירה. נספח א — …",
                      "פרק 4 — סיכום…")
        .replace_text("לפי תשריט (DWG)", "לפי תשריט")
        .recompute_default_badges()
        .filter_priority_items(lambda it: "תא שטח 9" not in it)
        .rewrite_toc(_NEW_TOC_ROWS)
        .save("audit_report_24.3.html"))

API conventions
---------------
* Every mutation returns ``self`` (fluent / chainable).
* Every operation appends a one-line entry to ``self.log`` so you can
  print the operation trail after a chain runs.
* Locator failures raise ``HTMLNotFoundError`` with a snippet of the
  missing marker so it's obvious what shifted.
* The module is pure-string-level: no DOM parser. Couples to
  ``report_generator`` template structure (verdict-class spans, TOC
  shape, badge HTML, subsection/chapter divs). If those templates change
  shape, update the constants at the top of this file.

The module is dependency-free apart from stdlib + ``re``.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Callable, Iterable


__all__ = [
    "HTMLNotFoundError",
    "ReportSurgery",
    "DEFAULT_BADGE_LABELS_HE",
    "VERDICT_CLASSES",
]


# ────────────────────────────────────────────────────────────────────────────
# Couplings to report_generator template shape — tweak here if those change
# ────────────────────────────────────────────────────────────────────────────

#: Verdict-class names used by ``report_generator`` on the right-hand cell of
#: every audit-table row. ``count_verdicts`` tallies these per chapter scope.
VERDICT_CLASSES = ("v-ok", "v-fail", "v-rev", "v-na", "v-miss")

#: How verdict classes map to badge buckets. ``v-miss`` (not_submitted) and
#: ``v-fail`` both feed the "fail" bucket; ``v-na`` is its own bucket only in
#: §2 (the discipline section drops it). See ``recompute_default_badges``.
_BADGE_BUCKET_FOR_VERDICT = {
    "v-ok":   "ok",
    "v-fail": "fail",
    "v-miss": "fail",
    "v-rev":  "review",
    "v-na":   "na",
}

#: Hebrew badge labels rendered by ``_badges_table`` in each chapter, mapped
#: to their bucket key. Override per-chapter when calling
#: ``recompute_badges`` directly. The full default mapping is sufficient for
#: any report generated by the current ``report_generator``.
DEFAULT_BADGE_LABELS_HE: dict[str, dict[str, str]] = {
    "sec-2": {
        "ok":      "תקינים בתוכן",
        "fail":    "ליקויים בתוכן",
        "review":  "נדרשת השלמה",
        "unknown": "לא ניתנים לבדיקה",
        "na":      "לא רלוונטיים",
    },
    "sec-3": {
        "ok":      "תקינים במדיניות",
        "fail":    "סטיות ממדיניות",
        "review":  "נדרשת השלמה",
        "unknown": "לא ניתנים לבדיקה",
    },
    "sec-4": {
        "ok":     "תקינים",
        "fail":   "נדרשים תיקונים",
        "review": "נדרשת השלמה",
    },
}

# Markers used to find next-sibling boundaries when removing a section.
_BLOCK_BREAK_MARKERS = (
    '<div class="subsection"',
    '<div class="chapter"',
    '<div class="chapter ',  # multi-class chapters: sidecar-chapter / cad-chapter / chat-chapter
    '<div class="appendix-divider',
    '</body>',
)


# ────────────────────────────────────────────────────────────────────────────
# Errors
# ────────────────────────────────────────────────────────────────────────────

class HTMLNotFoundError(RuntimeError):
    """The expected marker (chapter/subsection/etc) wasn't found in the HTML.

    Raised by every locator so the operation trail surfaces the exact
    missing marker rather than a generic IndexError.
    """


# ────────────────────────────────────────────────────────────────────────────
# Main surgery class
# ────────────────────────────────────────────────────────────────────────────

class ReportSurgery:
    """Fluent HTML editor for audit_report.html.

    Mutations chain. Read-only inspection (``find_anchor_pos``,
    ``count_verdicts``) does not append to the log.
    """

    def __init__(self, html: str) -> None:
        self.html = html
        self.log: list[str] = []

    # -- I/O ----------------------------------------------------------------
    @classmethod
    def from_path(cls, path: str | Path) -> "ReportSurgery":
        return cls(Path(path).read_text(encoding="utf-8"))

    def save(self, path: str | Path) -> "ReportSurgery":
        Path(path).write_text(self.html, encoding="utf-8")
        return self

    def __len__(self) -> int:
        return len(self.html)

    def __str__(self) -> str:
        return self.html

    # -- Read-only inspection ----------------------------------------------
    def find_anchor_pos(self, anchor_id: str) -> int:
        """Return start position of the ``<div … id='anchor_id'>`` tag.

        Tolerates extra classes on the div (e.g. ``cad-chapter`` /
        ``sidecar-chapter``). Raises ``HTMLNotFoundError`` if missing.
        """
        m = re.search(rf'<div [^>]*id="{re.escape(anchor_id)}"', self.html)
        if not m:
            raise HTMLNotFoundError(f"no <div id='{anchor_id}'> in HTML")
        return m.start()

    def _find_next_block_start(self, after_pos: int) -> int:
        """Return position of the next block break (subsection/chapter/body
        close) at or after ``after_pos``. Used to bound a block being removed.
        """
        candidates = []
        for marker in _BLOCK_BREAK_MARKERS:
            i = self.html.find(marker, after_pos)
            if i > 0:
                candidates.append(i)
        if not candidates:
            raise HTMLNotFoundError(
                f"no block break marker found after position {after_pos}"
            )
        return min(candidates)

    def count_verdicts(self, chapter_id: str) -> dict[str, int]:
        """Tally verdict-class ``<span>`` hits within the named chapter."""
        start = self.find_anchor_pos(chapter_id)
        end = self._find_next_chapter_start(start)
        slice_ = self.html[start:end]
        return {
            cls: len(re.findall(rf'class="{cls}">', slice_))
            for cls in VERDICT_CLASSES
        }

    def _find_next_chapter_start(self, after_pos: int) -> int:
        """Return position of the next chapter open, or end-of-body.

        Markers:
          - ``<div class="chapter"`` — covers both ``<div class="chapter">``
            (TOC) and ``<div class="chapter" id="...">`` (numbered chapters)
            in one pattern. No trailing ``>`` so attributes can follow.
          - ``<div class="chapter `` — multi-class chapters (e.g.
            ``sidecar-chapter`` / ``cad-chapter`` / ``chat-chapter``)
          - ``<div class="appendix-divider`` — appendix divider page
          - ``</body>`` — end of document
        """
        candidates = []
        for marker in ('<div class="chapter"',
                       '<div class="chapter ',
                       '<div class="appendix-divider',
                       '</body>'):
            i = self.html.find(marker, after_pos + 1)
            if i > 0:
                candidates.append(i)
        if not candidates:
            return len(self.html)
        return min(candidates)

    # -- Block removal -----------------------------------------------------
    def remove_subsection(self, sec_id: str) -> "ReportSurgery":
        """Delete the subsection block opening with ``id='sec_id'`` up to
        but not including the next subsection / chapter open.
        """
        start = self.find_anchor_pos(sec_id)
        end = self._find_next_block_start(start + 1)
        removed = end - start
        self.html = self.html[:start] + self.html[end:]
        self.log.append(f"remove_subsection({sec_id!r}) removed {removed:,} chars")
        return self

    def remove_chapter(self, chapter_id: str) -> "ReportSurgery":
        """Delete the chapter opening with ``id='chapter_id'`` up to but not
        including the next chapter / appendix divider / ``</body>``.

        For removing multiple consecutive chapters at once, prefer
        ``remove_chapter_range``.
        """
        start = self.find_anchor_pos(chapter_id)
        end = self._find_next_chapter_start(start)
        removed = end - start
        self.html = self.html[:start] + self.html[end:]
        self.log.append(f"remove_chapter({chapter_id!r}) removed {removed:,} chars")
        return self

    def remove_chapter_range(self, first_id: str, stop_id: str) -> "ReportSurgery":
        """Remove from ``first_id`` (inclusive) up to ``stop_id`` (exclusive).

        Useful for cutting consecutive chapters in one shot (e.g. §2א/2ב/2ג
        between sec-m4-sidecar and sec-3). When ``stop_id`` is the special
        marker ``"</body>"``, cuts everything from ``first_id`` to end of
        body.
        """
        start = self.find_anchor_pos(first_id)
        if stop_id == "</body>":
            end = self.html.find("</body>", start)
            if end < 0:
                raise HTMLNotFoundError("no </body> in HTML")
        else:
            end = self.find_anchor_pos(stop_id)
        if end <= start:
            raise HTMLNotFoundError(
                f"stop_id {stop_id!r} appears at or before first_id {first_id!r}"
            )
        removed = end - start
        self.html = self.html[:start] + self.html[end:]
        self.log.append(
            f"remove_chapter_range({first_id!r}…{stop_id!r}) removed {removed:,} chars"
        )
        return self

    # -- Subsection mutation ----------------------------------------------
    def rename_subsection(self, sec_id: str, new_heading_text: str) -> "ReportSurgery":
        """Replace the inner text of the ``<h3 class='subsection-num'>``
        inside the named subsection. ``new_heading_text`` typically starts
        with the new number (e.g. ``'3.4 תנועה — רחבות כיבוי אש'``).
        """
        start = self.find_anchor_pos(sec_id)
        end = self._find_next_block_start(start + 1)
        pat = re.compile(
            r'(<h3 class="subsection-num">)([^<]*)(</h3>)',
            re.DOTALL,
        )
        scope = self.html[start:end]
        new_scope, n = pat.subn(rf'\g<1>{re.escape(new_heading_text).replace(chr(92), "")}\g<3>',
                                scope, count=1)
        if n == 0:
            raise HTMLNotFoundError(
                f"no <h3 class='subsection-num'> inside {sec_id!r}"
            )
        # re.escape would munge unicode; just splice directly:
        new_scope = pat.sub(rf'\g<1>{new_heading_text}\g<3>', scope, count=1)
        self.html = self.html[:start] + new_scope + self.html[end:]
        self.log.append(
            f"rename_subsection({sec_id!r}) → {new_heading_text!r}"
        )
        return self

    def extract_subsection_rows(self, sec_id: str) -> str:
        """Return the ``<tr>…</tr>`` rows inside a subsection's audit
        ``<tbody>``. Used internally by ``merge_subsection_rows``; exposed
        for callers who want to inspect content before merging.
        """
        start = self.find_anchor_pos(sec_id)
        tbody_start = self.html.find("<tbody>", start)
        if tbody_start < 0:
            raise HTMLNotFoundError(f"no <tbody> in subsection {sec_id!r}")
        tbody_end = self.html.find("</tbody>", tbody_start)
        if tbody_end < 0:
            raise HTMLNotFoundError(f"unclosed <tbody> in subsection {sec_id!r}")
        return self.html[tbody_start + len("<tbody>"): tbody_end]

    def merge_subsection_rows(
        self,
        into_id: str,
        from_ids: Iterable[str],
        *,
        drop_sources: bool = True,
    ) -> "ReportSurgery":
        """Pull ``<tr>`` rows from each ``from_ids`` subsection's tbody,
        append them to ``into_id``'s tbody. If ``drop_sources`` (default),
        the source subsections are then deleted.
        """
        from_ids = list(from_ids)
        # Extract first so we don't disturb offsets, then splice + delete.
        rows = [self.extract_subsection_rows(sid) for sid in from_ids]
        merged_rows = "".join(rows)
        # Splice into the into_id's tbody (before </tbody>).
        into_start = self.find_anchor_pos(into_id)
        into_tbody_end = self.html.find("</tbody>", into_start)
        if into_tbody_end < 0:
            raise HTMLNotFoundError(f"no </tbody> in {into_id!r}")
        self.html = (
            self.html[:into_tbody_end]
            + merged_rows
            + self.html[into_tbody_end:]
        )
        self.log.append(
            f"merge_subsection_rows({into_id!r} ← {from_ids!r}); "
            f"+{len(merged_rows):,} chars"
        )
        if drop_sources:
            for sid in from_ids:
                # remove_subsection re-locates each time — safe after splice.
                self.remove_subsection(sid)
        return self

    # -- Insertion ---------------------------------------------------------
    def insert_html_at_subsection_end(
        self,
        sec_id: str,
        html_block: str,
    ) -> "ReportSurgery":
        """Insert ``html_block`` at the end of the named subsection, after
        the closing ``</table>`` of its audit table (if any). Useful for
        appending an external comment block to a section.
        """
        start = self.find_anchor_pos(sec_id)
        # Insertion point: end of audit table if present, else just before
        # the next block break.
        table_end = self.html.find("</table>", start)
        next_block = self._find_next_block_start(start + 1)
        if 0 < table_end < next_block:
            insert_at = table_end + len("</table>")
        else:
            insert_at = next_block
        self.html = self.html[:insert_at] + html_block + self.html[insert_at:]
        self.log.append(
            f"insert_html_at_subsection_end({sec_id!r}); +{len(html_block):,} chars"
        )
        return self

    def insert_html_after_chapter(
        self,
        chapter_id: str,
        html_block: str,
    ) -> "ReportSurgery":
        """Insert ``html_block`` immediately after the closing of the named
        chapter (before the next chapter opens).
        """
        start = self.find_anchor_pos(chapter_id)
        insert_at = self._find_next_chapter_start(start)
        self.html = self.html[:insert_at] + html_block + self.html[insert_at:]
        self.log.append(
            f"insert_html_after_chapter({chapter_id!r}); +{len(html_block):,} chars"
        )
        return self

    # -- TOC ---------------------------------------------------------------
    def rewrite_toc(self, rows: list[dict] | str) -> "ReportSurgery":
        """Replace the entire TOC ``<table class='toc'>`` body.

        ``rows`` may be a pre-rendered HTML string of ``<tr>…</tr>`` rows,
        or a list of dicts each with keys: ``kind`` (``'main'`` or
        ``'sub'``), ``num`` (e.g. ``'3.4'``), ``title`` (display text),
        ``anchor`` (id without leading ``#``).
        """
        if isinstance(rows, list):
            rendered = "".join(self._toc_row(**r) for r in rows)
        else:
            rendered = rows
        m = re.search(r'<table class="toc">\s*', self.html)
        if not m:
            raise HTMLNotFoundError("no <table class='toc'> in HTML")
        close = self.html.find("</table>", m.end())
        if close < 0:
            raise HTMLNotFoundError("unclosed TOC table")
        self.html = self.html[:m.end()] + rendered + "\n      " + self.html[close:]
        self.log.append(f"rewrite_toc — {len(rendered):,} chars of <tr> rows")
        return self

    @staticmethod
    def _toc_row(kind: str, num: str, title: str, anchor: str) -> str:
        kind_cls = "main" if kind == "main" else "sub"
        return (
            f'<tr><td class="title {kind_cls}">'
            f'<a href="#{anchor}">{num} {title}</a></td>'
            f'<td class="page"><a href="#{anchor}"></a></td></tr>'
        )

    # -- Badge recomputation ----------------------------------------------
    def recompute_badges(
        self,
        scope_chapter_id: str,
        counts: dict[str, int],
        badge_labels_he: dict[str, str],
    ) -> "ReportSurgery":
        """Replace the digit inside each badge cell within the named chapter.

        ``counts``         — bucket name → new count (e.g. ``{'ok': 5, 'fail': 15}``)
        ``badge_labels_he`` — bucket name → Hebrew label rendered in the
                              badge's ``<div class='label'>`` (used to find
                              the cell).
        """
        start = self.find_anchor_pos(scope_chapter_id)
        end = self._find_next_chapter_start(start)
        scope = self.html[start:end]
        before_scope_len = len(scope)
        misses = []
        for bucket, label_he in badge_labels_he.items():
            n = counts.get(bucket)
            if n is None:
                continue
            pat = re.compile(
                r'(<td class="[a-z]+"><div class="num">)\d+'
                r'(</div><div class="label">' + re.escape(label_he) + r'</div></td>)'
            )
            new_scope, n_subs = pat.subn(rf'\g<1>{n}\g<2>', scope, count=1)
            if n_subs == 0:
                misses.append(label_he)
            else:
                scope = new_scope
        self.html = self.html[:start] + scope + self.html[end:]
        msg = f"recompute_badges({scope_chapter_id!r}) — set {counts}"
        if misses:
            msg += f"; MISSED labels: {misses}"
        self.log.append(msg)
        if misses:
            # Don't fail outright — caller may have removed some badges.
            # The log entry preserves the audit trail.
            pass
        return self

    def recompute_default_badges(
        self,
        *,
        chapter_2_id: str = "sec-2",
        chapter_3_id: str = "sec-3",
        chapter_4_id: str = "sec-4",
    ) -> "ReportSurgery":
        """Convenience: tally verdicts in §2 and §3, then update both
        chapter badges plus the §4 final-summary badges.

        Assumes the default Hebrew labels (see ``DEFAULT_BADGE_LABELS_HE``).
        §4 totals are §2 + §3 (per the engine's ``_summary_badge_counts``).
        """
        v2 = self.count_verdicts(chapter_2_id)
        v3 = self.count_verdicts(chapter_3_id)

        def bucket_counts(v: dict[str, int]) -> dict[str, int]:
            out: dict[str, int] = {}
            for cls, n in v.items():
                bucket = _BADGE_BUCKET_FOR_VERDICT.get(cls)
                if bucket is None:
                    continue
                out[bucket] = out.get(bucket, 0) + n
            return out

        c2 = bucket_counts(v2)
        c3 = bucket_counts(v3)
        # Both engines omit "unknown" in practice; set to 0 if absent.
        c2.setdefault("unknown", 0)
        c3.setdefault("unknown", 0)
        c2.setdefault("na", 0)
        # §4 final = §2 ok/fail/review + §3 ok/fail/review
        c4 = {
            "ok":     c2.get("ok", 0) + c3.get("ok", 0),
            "fail":   c2.get("fail", 0) + c3.get("fail", 0),
            "review": c2.get("review", 0) + c3.get("review", 0),
        }
        self.recompute_badges(chapter_2_id, c2, DEFAULT_BADGE_LABELS_HE["sec-2"])
        self.recompute_badges(chapter_3_id, c3, DEFAULT_BADGE_LABELS_HE["sec-3"])
        self.recompute_badges(chapter_4_id, c4, DEFAULT_BADGE_LABELS_HE["sec-4"])
        return self

    # -- Priority list -----------------------------------------------------
    def transform_priority_items(
        self,
        transform: Callable[[str], str | None],
        *,
        renumber: bool = True,
    ) -> "ReportSurgery":
        """For each ``<li>`` inside ``<ol class='priority-list'>``, call
        ``transform(item_html)``. Return value ``None`` drops the item;
        otherwise the returned string replaces it. When ``renumber`` is
        true (default), the leading ``<li>N.`` digit is rewritten 1..N
        after filtering.
        """
        m_ol = re.search(r'<ol class="priority-list">', self.html)
        if not m_ol:
            self.log.append("transform_priority_items: no priority-list found")
            return self
        ol_start = m_ol.end()
        m_close = re.search(r'</ol>', self.html[ol_start:])
        if not m_close:
            raise HTMLNotFoundError("unclosed <ol class='priority-list'>")
        ol_end = ol_start + m_close.start()
        ol_content = self.html[ol_start:ol_end]

        items = re.findall(r'<li>.*?</li>', ol_content, re.DOTALL)
        before = len(items)
        result: list[str] = []
        for it in items:
            out = transform(it)
            if out is None:
                continue
            result.append(out)
        if renumber:
            result = [
                re.sub(r'^<li>\d+\.\s', f'<li>{i}. ', it, count=1)
                for i, it in enumerate(result, start=1)
            ]
        self.html = self.html[:ol_start] + "".join(result) + self.html[ol_end:]
        self.log.append(
            f"transform_priority_items: {before} → {len(result)} items"
            f"{' (renumbered)' if renumber else ''}"
        )
        return self

    def filter_priority_items(
        self,
        predicate: Callable[[str], bool],
        *,
        renumber: bool = True,
    ) -> "ReportSurgery":
        """Convenience: drop any priority item where ``predicate(item)`` is
        false. Keep everything else verbatim.
        """
        return self.transform_priority_items(
            lambda it: it if predicate(it) else None,
            renumber=renumber,
        )

    # -- Plain text -------------------------------------------------------
    def replace_text(self, old: str, new: str, *, count: int = 0) -> "ReportSurgery":
        """Plain ``str.replace``. ``count`` 0 = replace all (default).

        Raises ``HTMLNotFoundError`` if ``old`` is not present at all —
        catches the common "I edited the source string but not the
        marker" mistake.
        """
        if old not in self.html:
            raise HTMLNotFoundError(
                f"replace_text: old string not found "
                f"(first 60 chars: {old[:60]!r})"
            )
        if count <= 0:
            self.html = self.html.replace(old, new)
        else:
            self.html = self.html.replace(old, new, count)
        self.log.append(
            f"replace_text({old[:30]!r}…) → ({new[:30]!r}…)"
        )
        return self

    def replace_text_optional(self, old: str, new: str) -> "ReportSurgery":
        """Like ``replace_text`` but silently no-ops if ``old`` is absent."""
        if old in self.html:
            self.html = self.html.replace(old, new)
            self.log.append(
                f"replace_text_optional({old[:30]!r}…) → ({new[:30]!r}…)"
            )
        else:
            self.log.append(
                f"replace_text_optional({old[:30]!r}…) — not present, skipped"
            )
        return self
